build-gcp:
	python3 -m pip install -r requirements-gcp.txt

build-aws:
	python3 -m pip install -r requirements-gcp.txt

build-azure:
	python3 -m pip install -r requirements-azure.txt

test:
	pytest 

lint:
	isort
	python3 -m black *.py
